server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: cambio-service
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin123
management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/
  tracing:
    sampling:
      probability: 1.0  # Para garantir que todas as requisições sejam rastreadas
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs