server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: api-gateway
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/
  tracing:
    sampling:
      probability: 1.0  # Para garantir que todas as requisições sejam rastreadas