server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: book-service
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin123
management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/
  tracing:
    sampling:
      probability: 1.0  # Para garantir que todas as requisições sejam rastreadas
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs